- name: install docker
  hosts: webservers
  become: true
  gather_facts: false
  tasks:
    - name: COPY compose.yaml to remote server
      copy:
        src: /home/kubernates/mywebapp/compose.yaml
        dest: /home/compose.yaml
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Update apt and install docker-ce
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: true
      loop:
        - docker-ce
        - aptitude
        - apt-transport-https
        - curl
        - gnupg-agent
        - software-properties-common
        - python3-pip
    - name: add docker user to docker group
      user:
        name: fmuyassarov
        groups: docker
        append: yes
    - name: Create worpress stack
      community.docker.docker_compose:
        project_src: /home
        files:
        - compose.yaml
